version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 teste_labhacker.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SOCIAL_AUTH_CUSTOM_GITHUB_KEY=c429bbe2b90bc69947ef
      - SOCIAL_AUTH_CUSTOM_GITHUB_SECRET=8a9a08b3785d854ad6632466d59f7ad2cf677c11
      - ENV=development  

volumes:
  postgres_data:

